SET hiveconf:dbname;

CREATE OR REPLACE VIEW ${hiveconf:dbname}.FileObjectAccessedOrChanged_windows AS
SELECT
    event_time          AS TimeOfEvent,
    ""                  AS TimeReceived,
    ""                  AS DeviceReceived,
    ""                  AS TimeLoaded,
    ""                  AS SyslogFacility,
    ""                  AS SyslogPriority,
    "Microsoft"         AS ReportingVendor,
    "Windows"           AS ReportingProduct,
    "2008+"             AS ReportingVersion,
    event_id            AS EventID,
    event_description   AS EventName,
    "ObjectAccess"      AS EventLogType,
    subject_logonid     AS SequenceID,
    ""                  AS Severity,
    subject_username    AS SourceUserID,
    ""                  AS SourceHost,
    ip_address          AS SourceIP,
    ip_port             AS SourcePort,
    ""                  AS SourceMac,
    subject_domainname  AS SourceDomain,
    ""                  AS ReportingHost,
    ""                  AS ReportingIP,
    ""                  AS ReportingPort,
    ""                  AS ReportingMac,
    target_username     AS DestinationUserID,
    ""                  AS DestinationHost,
    ""                  AS DestinationIP,
    ""                  AS DestinationPort,
    ""                  AS DestinationMac,
    target_domainname   AS DestinationDomain,
    event_description   AS Action,
    object_name         AS ObjectName,
    handle_id           AS ObjectID,
    object_type         AS ObjectType,
    ""                  AS ObjectCreateTime,
    ""                  AS ObjectModifiedTime,
    ""                  AS ObjectPath,
    accesses            AS ObjectPermission,
    ""                  AS ObjectHash,
    ""                  AS ObjectSize,
    ""                  AS OriginalObjectName,
    ""                  AS OriginalObjectID,
    ""                  AS OriginalObjectType,
    ""                  AS OriginalObjectCreateTime,
    ""                  AS OriginalObjectModifiedTime,
    ""                  AS OriginalObjectPath,
    ""                  AS OriginalObjectPermission,
    ""                  AS OriginalObjectHash,
    ""                  AS OriginalObjectSize,
    year,
    month,
    day
FROM
    ${hiveconf:dbname}.windows_view_partition
WHERE
    event_id IN (4656, 4658, 4659, 4660, 4663, 4664, 4670, 4691, 4907) AND (object_type='File' OR event_id IN (4658));


CREATE OR REPLACE VIEW ${hiveconf:dbname}.FileObjectAccessedOrChanged
(
    TimeOfEvent,
    TimeReceived,
    DeviceReceived,
    TimeLoaded,
    SyslogFacility,
    SyslogPriority,
    ReportingVendor,
    ReportingProduct,
    ReportingVersion,
    EventID,
    EventName,
    EventLogType,
    SequenceID,
    Severity,
    SourceUserID,
    SourceHost,
    SourceIP,
    SourcePort,
    SourceMac,
    SourceDomain,
    ReportingHost,     
    ReportingIP,       
    ReportingPort,     
    ReportingMac,      
    DestinationUserID, 
    DestinationHost,   
    DestinationIP,     
    DestinationPort,   
    DestinationMac,    
    DestinationDomain, 
    Action,
    ObjectName,
    ObjectID,
    ObjectType,
    ObjectCreateTime,
    ObjectModifiedTime,
    ObjectPath,
    ObjectPermission,
    ObjectHash,
    ObjectSize,
    OriginalObjectName,
    OriginalObjectID,
    OriginalObjectType,
    OriginalObjectCreateTime,
    OriginalObjectModifiedTime,
    OriginalObjectPath,
    OriginalObjectPermission,
    OriginalObjectHash,
    OriginalObjectSize,
    year,
    month,
    day
) AS
SELECT * FROM ${hiveconf:dbname}.FileObjectAccessedOrChanged_windows;
