SET hiveconf:dbname;

CREATE OR REPLACE VIEW ${hiveconf:dbname}.NetworkConnection_wgtraffic AS
SELECT
    event_time             AS TimeOfEvent,
    ''                     AS TimeReceived,
    ''                     AS DeviceReceived,
    ''                     AS TimeLoaded,
    ''                     AS SyslogFacility,
    ''                     AS SyslogPriority,
    'WatchGuard'           AS ReportingVendor,
    'Traffic'              AS ReportingProduct,
    ''                     AS ReportingVersion,
    ''                     AS EventID,
    ''                     AS EventName,
    'Network'              AS EventLogType,
    sid                    AS SequenceID,
    ''                     AS Severity,
    regexp_extract(info_3, 'src_user=([^ ]+)', 1)  AS SourceUserID,
    ''                     AS SourceHost,
    src_ip                 AS SourceIP,
    src_port               AS SourcePort,
    ''                     AS SourceMac,
    ''                     AS SourceDomain,
    ''                     AS ReportingHost,
    ''                     AS ReportingIP,
    ''                     AS ReportingPort,
    ''                     AS ReportingMac,
    ''                     AS DestinationUserID,
    ''                     AS DestinationHost,
    dst_ip                 AS DestinationIP,
    dst_port               AS DestinationPort,
    ''                     AS DestinationMac,
    regexp_extract(info_5, 'dstname=([^ ]+)', 1)   AS DestinationDomain,
    protocol               AS Protocol,
    regexp_extract(info_6, 'arg=([^ ]+)', 1)       AS URL,
    ''                     AS CLFUserAgent,
    ''                     AS CLFCookies,
    IF(instr(info_1, 'rcvd_bytes') <> 0 AND instr(info_2, 'sent_bytes') <> 0, IF (cast(regexp_extract(info_1, 'rcvd_bytes=(\\d+)', 1) AS int) < cast(regexp_extract(info_2, 'sent_bytes=(\\d+)', 1) AS int), 'Upload', 'Download'), '-') AS CLFMethod,
    year,
    month, 
    day
FROM ${hiveconf:dbname}.wgtraffic_view_partition;


CREATE OR REPLACE VIEW ${hiveconf:dbname}.NetworkConnection(
    TimeOfEvent,
    TimeReceived,
    DeviceReceived,
    TimeLoaded,
    SyslogFacility,
    SyslogPriority,
    ReportingVendor,
    ReportingProduct,
    ReportingVersion,
    EventID,
    EventName,
    EventLogType,
    SequenceID,
    Severity,
    SourceUserID,
    SourceHost,
    SourceIP,
    SourcePort,
    SourceMac,
    SourceDomain,
    ReportingHost,
    ReportingIP,
    ReportingPort,
    ReportingMac,
    DestinationUserID,
    DestinationHost,
    DestinationIP,
    DestinationPort,
    DestinationMac,
    DestinationDomain,
    Protocol,
    URL,
    CLFUserAgent,
    CLFCookies,
    CLFMethod,
    year,
    month, 
    day
) AS
SELECT * FROM ${hiveconf:dbname}.NetworkConnection_wgtraffic;
